const { Client } = require('discord.js');
const { Riffy, Player } = require('riffy');

const STOP_CANDIDATE_TTL_MS = 15000;
const STOP_EVENT_TTL_MS = 15000;

/**
 * Makes /stop and the Now Playing Stop button authoritative.
 *
 * Riffy treats Player.stop() like any other TrackEnd. With autoplay enabled,
 * an empty queue becomes queueEnd and player.js immediately starts autoplay.
 * If a queued track exists, Riffy can start that track even earlier. That means
 * the command/button's destroy() may run only after a replacement track has
 * already started, at which point the active-playback destroy guard correctly
 * refuses to kill the new track.
 *
 * We identify only the two user-facing STOP interactions, arm the next
 * Player.stop() call for that player, clear queue/loop before stopping, and
 * suppress the queueEnd generated by that intentional stop. Skip and natural
 * track endings are deliberately untouched.
 */
function installIntentionalStopGuard() {
    if (global.__dfordogIntentionalStopGuardInstalled) return;
    global.__dfordogIntentionalStopGuardInstalled = true;

    if (Client?.prototype && !Client.prototype.__dfordogStopIntentCaptureInstalled) {
        const originalClientEmit = Client.prototype.emit;

        Client.prototype.emit = function(eventName, ...args) {
            if (eventName === 'interactionCreate') {
                const interaction = args[0];
                const isSlashStop = interaction?.isChatInputCommand?.() === true && interaction.commandName === 'stop';
                const isPanelStop = interaction?.isButton?.() === true && interaction.customId === 'stopTrack';

                if (isSlashStop || isPanelStop) {
                    const guildId = interaction.guildId;
                    const player = guildId ? this.riffy?.players?.get(guildId) : null;
                    const cachedMember = guildId && interaction.user?.id
                        ? interaction.guild?.members?.cache?.get(interaction.user.id)
                        : null;
                    const memberVoiceChannelId = interaction.member?.voice?.channelId ||
                        interaction.member?.voice?.channel?.id ||
                        cachedMember?.voice?.channelId ||
                        null;
                    const playerVoiceChannelId = player?.voiceChannel ||
                        player?.connection?.voiceChannel ||
                        player?.connection?.voice?.channelId ||
                        null;

                    // Mirror the normal voice-control requirement before arming.
                    // If the interaction is rejected, no future unrelated stop/skip
                    // should accidentally inherit the marker.
                    const appearsAuthorized = !!player && !!memberVoiceChannelId &&
                        (!playerVoiceChannelId || memberVoiceChannelId === playerVoiceChannelId);

                    if (appearsAuthorized) {
                        player.__dfordogIntentionalStopCandidate = {
                            at: Date.now(),
                            source: isSlashStop ? '/stop' : 'now-playing-stop',
                            client: this
                        };

                        console.log(`[ STOP GUARD ] Armed ${isSlashStop ? '/stop' : 'panel Stop'} for guild ${guildId}.`);
                    }
                }
            }

            return originalClientEmit.call(this, eventName, ...args);
        };

        Object.defineProperty(Client.prototype, '__dfordogStopIntentCaptureInstalled', {
            value: true,
            configurable: false,
            enumerable: false,
            writable: false
        });
    }

    if (Player?.prototype && !Player.prototype.__dfordogIntentionalStopPatchInstalled) {
        const originalStop = Player.prototype.stop;

        Player.prototype.stop = function(...args) {
            const candidate = this.__dfordogIntentionalStopCandidate;
            delete this.__dfordogIntentionalStopCandidate;

            if (candidate) {
                const candidateAge = Date.now() - candidate.at;

                if (candidateAge <= STOP_CANDIDATE_TTL_MS) {
                    // STOP means stop the whole playback session, not Skip. Clear any
                    // queued songs and loop state before Riffy processes TrackEnd so
                    // it cannot synchronously start another queued/looped track.
                    try {
                        this.queue?.clear?.();
                    } catch (_) {}

                    if (this.loop && this.loop !== 'none') {
                        this.loop = 'none';
                    }

                    this.__dfordogIntentionalStop = {
                        at: Date.now(),
                        source: candidate.source,
                        client: candidate.client
                    };

                    console.log(`[ STOP GUARD ] Intentional stop committed for guild ${this.guildId}; source=${candidate.source}. Queue cleared and loop disabled.`);
                }
            }

            return originalStop.apply(this, args);
        };

        Object.defineProperty(Player.prototype, '__dfordogIntentionalStopPatchInstalled', {
            value: true,
            configurable: false,
            enumerable: false,
            writable: false
        });
    }

    if (Riffy?.prototype && !Riffy.prototype.__dfordogIntentionalQueueEndPatchInstalled) {
        const originalRiffyEmit = Riffy.prototype.emit;

        Riffy.prototype.emit = function(eventName, ...args) {
            if (eventName === 'queueEnd') {
                const player = args[0];
                const marker = player?.__dfordogIntentionalStop;

                if (marker) {
                    delete player.__dfordogIntentionalStop;
                    const markerAge = Date.now() - marker.at;

                    if (markerAge <= STOP_EVENT_TTL_MS) {
                        // Keep local state unambiguously idle. The command/button can
                        // now destroy the player (normal mode), or leave it connected
                        // and silent (24/7 mode), without autoplay racing in first.
                        player.playing = false;
                        player.paused = false;
                        try {
                            player.queue?.clear?.();
                        } catch (_) {}

                        const client = marker.client;
                        if (client?.statusManager?.onTrackEnd) {
                            Promise.resolve(client.statusManager.onTrackEnd(player.guildId)).catch(() => {});
                        }

                        console.log(`[ STOP GUARD ] Suppressed queueEnd/autoplay for intentional stop in guild ${player.guildId}; source=${marker.source}.`);
                        return false;
                    }
                }
            }

            return originalRiffyEmit.call(this, eventName, ...args);
        };

        Object.defineProperty(Riffy.prototype, '__dfordogIntentionalQueueEndPatchInstalled', {
            value: true,
            configurable: false,
            enumerable: false,
            writable: false
        });
    }

    console.log('[ STOP GUARD ] v10 intentional-stop guard installed (/stop + panel Stop; Skip unaffected).');
}

installIntentionalStopGuard();

module.exports = { installIntentionalStopGuard };
